name: Docker Deployment to Heroku

on:
  push:
    branches:
      - main  # Or any other branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Heroku Container Registry
        uses: akhileshns/heroku-docker-login@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/wine01/web .

      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/wine01/web

      - name: Release Docker container on Heroku
        run: |
          heroku container:release web -a wine01
